{application,nitrogen,
             [{description,"My Nitrogen Web Project"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{nitrogen_app,[]}},
              {env,[]},
              {modules,[config_dyn,dynamic_compile,email,iaccess,iaccount,
                        igroup,index,misc,mobile,nitrogen_app,nitrogen_cowboy,
                        nitrogen_sup,player_info]}]}.
