{application,nitrogen,
             [{description,"My Nitrogen Web Project"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{nitrogen_app,[]}},
              {env,[]},
              {modules,[account,config_dyn,dynamic_compile,email,group,
                        iaccess,iaccount,igroup,index,misc,mobile,
                        nitrogen_app,nitrogen_cowboy,nitrogen_sup,
                        player_info]}]}.
